all: icon.png
	cp icon.png touch-icon-192x192.png
	sips -Z 57 icon.png --out apple-touch-icon-precomposed.png
	sips -Z 72 icon.png --out apple-touch-icon-72x72-precomposed.png
	sips -Z 76 icon.png --out apple-touch-icon-76x76-precomposed.png
	sips -Z 114 icon.png --out apple-touch-icon-114x114-precomposed.png
	sips -Z 120 icon.png --out apple-touch-icon-120x120-precomposed.png
	sips -Z 144 icon.png --out apple-touch-icon-144x144-precomposed.png
	sips -Z 152 icon.png --out apple-touch-icon-152x152-precomposed.png
	sips -Z 180 icon.png --out apple-touch-icon-180x180-precomposed.png

